# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ackoctl < Formula
  desc "CLI for aerospike-cluster-manager"
  homepage "https://github.com/aerospike-ce-ecosystem/ackoctl"
  version "0.3.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aerospike-ce-ecosystem/ackoctl/releases/download/v0.3.6/ackoctl_0.3.6_darwin_amd64.tar.gz"
      sha256 "e72477fef1b35e6377e15dbb42d2d6b80ee66566ee8925f2691cf13a6393cf6e"

      define_method(:install) do
        bin.install "ackoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aerospike-ce-ecosystem/ackoctl/releases/download/v0.3.6/ackoctl_0.3.6_darwin_arm64.tar.gz"
      sha256 "fb798bb7571a15a8ab20ace260776ffaee33e9610ddec7467e31a326a712c6c5"

      define_method(:install) do
        bin.install "ackoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aerospike-ce-ecosystem/ackoctl/releases/download/v0.3.6/ackoctl_0.3.6_linux_amd64.tar.gz"
      sha256 "37a5944bb52c9285cca1166432d0d76f81c4ae548b9b615ce0c3c19edca9ee1d"
      define_method(:install) do
        bin.install "ackoctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aerospike-ce-ecosystem/ackoctl/releases/download/v0.3.6/ackoctl_0.3.6_linux_arm64.tar.gz"
      sha256 "3e80cd14bca4abc6ac71bba98d5fc95270d6c598fd85bda81e29b27f05bf13ca"
      define_method(:install) do
        bin.install "ackoctl"
      end
    end
  end

  test do
    system "#{bin}/ackoctl", "version"
  end
end
